# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  gather_lyx_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: files
        run: |
          IFS=$'\n' files=($(find . -name '*.lyx'))
          len=${#files[@]}
          out="["
          for i in $(seq 1 $len); do  out+="\"${files[$((i-1))]}\"";   if [ $i == $((len - 1)) ];   then out+=","; fi; done
          out+="]"
          echo "::set-output name=matrix::$(echo $out)"
          
    outputs:
      matrix: ${{ steps.files.outputs.matrix }}
      
  # This workflow contains a single job called "build"
  build:
    needs: gather_lyx_files
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ fromJson(needs.gather_lyx_files.outputs.matrix) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Lyx2Pdf
        # You may pin to the exact commit or the version.
        # uses: vaggeliskls/lyx2pdf-action@71f15b95583d47e73906fe23fab84a2f4f561b24
        uses: vaggeliskls/lyx2pdf-action@v1
        with:
          # The root lyx file to be compiled
          root_file: ${{ matrix.files }}
          
      - name: Upload PDF
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./**/*.pdf
